

export const CREATE_SETNAME_POPUP = 'CREATE_SETNAME_POPUP';

export const POPUP_CONFIRMATION_TRUE = 'POPUP_CONFIRMATION_TRUE';

export const TOGGLE_ITEM = 'TOGGLE_ITEM';

export const BUY_ITEM_FROM_AUCTION = 'BUY_ITEM_FROM_AUCTION';

export const SELL_ITEM_FROM_INVENTORY = 'SELL_ITEM_FROM_INVENTORY';

export const SELECT_ITEM_TYPE = 'SELECT_ITEM_TYPE';

export const SELECT_TOGGLE_MODE = 'SELECT_TOGGLE_MODE';

export const POPUP_CONFIRMATION_FALSE='POPUP_CONFIRMATION_FALSE';

export const SAVE_NEW_NAME = 'SAVE_NEW_NAME';

export const FETCH_AUCTION_DATA = 'FETCH_AUCTION_DATA';

export const SET_PRICE_RANGE = 'SET_PRICE_RANGE';


